services:
  postgres:
    image: postgres:17
    container_name: detailing_booking_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      target: ${NODE_ENV:-development}
    container_name: detailing_booking_app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      DB_HOST: postgres
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - postgres

volumes:
  postgres_data: